name: Build APK on GitHub Cloud

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libssl-dev libffi-dev cmake libgdbm-dev sqlite3 libsqlite3-dev bzip2 libbz2-dev liblzma-dev lld
        sudo apt-get install -y libltdl-dev

    - name: Install Build Tools
      run: |
        pip install --upgrade pip setuptools wheel cython==0.29.36
        pip install "buildozer==1.5.0"

    - name: Pre-configure Android SDK Path Fix
      run: |
        mkdir -p ~/.buildozer/android/platform/
        
    - name: Build Android APK Package
      run: |
        yes y | buildozer -v android debug

    - name: Upload Finished APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TetyaAsyaApp-APK
        path: bin/*.apk
